"""Add blogger_id foreign key with name

Revision ID: d583657bcade
Revises: 
Create Date: 2025-06-10 20:41:36.424827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd583657bcade'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blogger_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_post_blogger_id', 'bloggers', ['blogger_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint('fk_post_blogger_id', type_='foreignkey')
        batch_op.drop_column('blogger_id')

    # ### end Alembic commands ###
